# Generated by Django 4.1.7 on 2023-03-27 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scan_receipt", "0003_scan_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="user",
        ),
    ]
